
include: "rules/common.smk"
include: "rules/preprocess.smk"
include: "rules/analyze.smk"
include: "rules/report.smk"


rule all:
    input:
        f"{OUTDIR}/report/summary.svg",
        [f"{prefix(s)}.curve.svg" for s in SAMPLES],
